// flow-typed signature: 3adf73c61d7ca03a03d3a93e96544a40
// flow-typed version: <<STUB>>/json-schema-faker_v^0.4.7/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-schema-faker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-schema-faker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-schema-faker/lib/index' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/az' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/cz' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/de_AT' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/de_CH' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/de' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/en_au_ocker' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/en_AU' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/en_BORK' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/en_CA' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/en_GB' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/en_IE' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/en_IND' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/en_US' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/en' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/es_MX' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/es' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/fa' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/fr_CA' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/fr' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/ge' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/id_ID' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/it' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/ja' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/ko' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/nb_NO' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/nep' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/nl' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/pl' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/pt_BR' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/ru' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/sk' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/sv' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/tr' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/uk' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/vi' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/zh_CN' {
  declare module.exports: any;
}

declare module 'json-schema-faker/locale/zh_TW' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-schema-faker/index' {
  declare module.exports: $Exports<'json-schema-faker'>;
}
declare module 'json-schema-faker/index.js' {
  declare module.exports: $Exports<'json-schema-faker'>;
}
declare module 'json-schema-faker/lib/index.js' {
  declare module.exports: $Exports<'json-schema-faker/lib/index'>;
}
declare module 'json-schema-faker/locale/az.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/az'>;
}
declare module 'json-schema-faker/locale/cz.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/cz'>;
}
declare module 'json-schema-faker/locale/de_AT.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/de_AT'>;
}
declare module 'json-schema-faker/locale/de_CH.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/de_CH'>;
}
declare module 'json-schema-faker/locale/de.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/de'>;
}
declare module 'json-schema-faker/locale/en_au_ocker.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/en_au_ocker'>;
}
declare module 'json-schema-faker/locale/en_AU.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/en_AU'>;
}
declare module 'json-schema-faker/locale/en_BORK.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/en_BORK'>;
}
declare module 'json-schema-faker/locale/en_CA.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/en_CA'>;
}
declare module 'json-schema-faker/locale/en_GB.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/en_GB'>;
}
declare module 'json-schema-faker/locale/en_IE.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/en_IE'>;
}
declare module 'json-schema-faker/locale/en_IND.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/en_IND'>;
}
declare module 'json-schema-faker/locale/en_US.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/en_US'>;
}
declare module 'json-schema-faker/locale/en.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/en'>;
}
declare module 'json-schema-faker/locale/es_MX.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/es_MX'>;
}
declare module 'json-schema-faker/locale/es.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/es'>;
}
declare module 'json-schema-faker/locale/fa.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/fa'>;
}
declare module 'json-schema-faker/locale/fr_CA.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/fr_CA'>;
}
declare module 'json-schema-faker/locale/fr.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/fr'>;
}
declare module 'json-schema-faker/locale/ge.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/ge'>;
}
declare module 'json-schema-faker/locale/id_ID.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/id_ID'>;
}
declare module 'json-schema-faker/locale/it.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/it'>;
}
declare module 'json-schema-faker/locale/ja.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/ja'>;
}
declare module 'json-schema-faker/locale/ko.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/ko'>;
}
declare module 'json-schema-faker/locale/nb_NO.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/nb_NO'>;
}
declare module 'json-schema-faker/locale/nep.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/nep'>;
}
declare module 'json-schema-faker/locale/nl.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/nl'>;
}
declare module 'json-schema-faker/locale/pl.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/pl'>;
}
declare module 'json-schema-faker/locale/pt_BR.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/pt_BR'>;
}
declare module 'json-schema-faker/locale/ru.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/ru'>;
}
declare module 'json-schema-faker/locale/sk.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/sk'>;
}
declare module 'json-schema-faker/locale/sv.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/sv'>;
}
declare module 'json-schema-faker/locale/tr.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/tr'>;
}
declare module 'json-schema-faker/locale/uk.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/uk'>;
}
declare module 'json-schema-faker/locale/vi.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/vi'>;
}
declare module 'json-schema-faker/locale/zh_CN.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/zh_CN'>;
}
declare module 'json-schema-faker/locale/zh_TW.js' {
  declare module.exports: $Exports<'json-schema-faker/locale/zh_TW'>;
}
